name: design_patterns_dart
description: Dart examples for all classic GoF design patterns.
version: 0.38.0
homepage: https://refactoring.guru/design-patterns
repository: https://github.com/RefactoringGuru/design-patterns-dart
issue_tracker: https://github.com/RefactoringGuru/design-patterns-dart/issue

environment:
  sdk: ^3.6.0

dependencies:
  collection: ^1.15.0
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  material_design_icons_flutter: ^7.0.7296
  
dev_dependencies:
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
